### ISSUE TITLE
Android Release Builds needs proguard-rules.pro when minifyEnabled

### ISSUE THREAD

**Issue by TobiasHeidingsfeld** [PostHog/posthog-flutter#107] opened 2024-05-29 09:48 UTC
### Version

4.4.1

### Steps to Reproduce

When adding Posthog and minifyEnabled is true in Gradle on Android the app breaks on startup. Solution is to add the following rules to proguard-rules.pro 

```

# posthog
-keep class com.posthog.** { *; }
-keep interface com.posthog.** { *; }

```

Feel free to add this to your documentation and let us know if there is anything else needed.

### Expected Result

Posthog not breaking the app

### Actual Result

Posthog breaking the app which can not start

**Comment by marandaneto** [comment] 2024-05-29 11:25
Hey @TobiasHeidingsfeld 
The PH Android SDK already ships all the rules
https://github.com/PostHog/posthog-android/blob/main/posthog-android/consumer-rules.pro
Strange that it's still crashing, do you know what exactly is causing this?

**Comment by TobiasHeidingsfeld** [comment] 2024-05-29 11:53
Could it be related to us using 

`proguardFiles getDefaultProguardFile('proguard-android.txt')`

in our build.gradle ? Will this override your consumer-rules.pro?

**Comment by marandaneto** [comment] 2024-05-29 11:58
> Could it be related to us using
> 
> `proguardFiles getDefaultProguardFile('proguard-android.txt')`
> 
> in our build.gradle ? Will this override your consumer-rules.pro?

I don't think so, the proguard rules are merged and taken into account.
https://github.com/PostHog/posthog-flutter/pull/108 works just fine for me.
Can you answer the questions [above](https://github.com/PostHog/posthog-flutter/issues/107#issuecomment-2137180111) so I can check if I spot anything strange in your config at least?

**Comment by marandaneto** [comment] 2024-05-29 12:11
Can be related to https://github.com/PostHog/posthog-android/issues/135 but we have not found out yet why nor if it's a one-off because no one else is reporting this nor I can reproduce it locally.

**Comment by marandaneto** [comment] 2024-06-11 06:39
@TobiasHeidingsfeld did you manage to reproduce the issue?

**Comment by marandaneto** [comment] 2024-06-17 06:33
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Closed by marandaneto** 2024-06-17 06:33 UTC
Labels: bug, question
