### ISSUE TITLE
warning: no rule to process file '/macos/Pods/PostHog/PostHog/Resources/PrivacyInfo.xcprivacy' of type 'text.xml' for architecture 'arm64' (in target 'PostHog' from project 'Pods')

### ISSUE THREAD

**Issue by stephane-archer** [PostHog/posthog-flutter#110] opened 2024-06-03 06:37 UTC
### Version

3.22.1

### Steps to Reproduce

just build an app using PostHog

### Expected Result

no warning

### Actual Result

warning: no rule to process file '/macos/Pods/PostHog/PostHog/Resources/PrivacyInfo.xcprivacy' of type 'text.xml' for architecture 'arm64' (in target 'PostHog' from project 'Pods')

**Comment by marandaneto** [comment] 2024-06-03 07:04
Dupe of https://github.com/PostHog/posthog-ios/issues/137
If you have tested the latest iOS version, see [comment](https://github.com/PostHog/posthog-ios/issues/137#issuecomment-2126525536), please reopen that issue.

**Closed by marandaneto** 2024-06-03 07:04 UTC
Labels: bug
