### ISSUE TITLE
identify() doesn't update user properties. 

### ISSUE THREAD

**Issue by choim4389** [PostHog/posthog-flutter#120] opened 2024-11-06 10:44 UTC
### Version

4.6.0

### Steps to Reproduce

Even though I used the same id, `identify()` doesn't update user properties(not once).  
How to update user's properties using flutter sdk?

### Expected Result

user properties must be changed if using same distinct id.

### Actual Result

user properties not changed.

**Comment by marandaneto** [comment] 2024-11-06 15:28
@choim4389 can you share the code snippet you use to update user properties and capture events?
Which SDK version?
Thanks

**Comment by choim4389** [comment] 2024-11-07 00:19
@marandaneto 
```
Posthog().identify(userId: 'test_id', properties: {'family_id': '2', 'test': 'test'});
Posthog().screen(screenName: screenName, properties: {'queryParameters': queryParameters});
```
it just set user property, and track screen.

I haven't checked on iOS.

**Comment by marandaneto** [comment] 2024-11-07 07:58
https://posthog.com/docs/libraries/flutter
See the Identifying users section, for user props, use the following props:

await Posthog().identify(
  userId: id, 
  userProperties: {"name": "Peter Griffin", "email": "peter@familyguy.com"},
  userPropertiesSetOnce: {"date_of_first_log_in": "2024-03-01"}
);

**Comment by choim4389** [comment] 2024-11-11 00:13
@marandaneto 
userProperties was a typo during writing.
`await Posthog().identify(userId: 'test_id', userProperties: {'family_id': '2', 'test': 'test'});` is not working.

**Comment by choim4389** [comment] 2024-11-11 02:08
It seems that the change will only be reflected if the app is reinstalled.

**Comment by marandaneto** [comment] 2024-11-11 09:03
Please provide a [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example) since everything works as expected when I test myself, it's likely something in your setup and I will happily reopen the issue.

**Comment by choim4389** [comment] 2024-11-12 01:00
It's so easy to reproduce.
```
Posthog().identify(userId: 'test_id', userProperties: {'family_id': '2'});
Posthog().screen(screenName: screenName, properties: {'queryParameters': queryParameters});
```
And then
```
Posthog().identify(userId: 'test_id', userProperties: {'family_id': '1'});
Posthog().screen(screenName: screenName, properties: {'queryParameters': queryParameters});
```

`family_id` not changed to '1'. `screen` and `capture` are both the same.

**Comment by choim4389** [comment] 2024-11-12 01:12
I looked into the `identify` function in the Android SDK, and it seems that once identify is performed, it does not work after that. 
Is this how it works? Then I can't change properties until the user changes (since the distinctId has to change)?

```
if (previousDistinctId != distinctId && !isIdentified) {
            // this has to be set before capture since this flag will be read during the event
            // capture
            synchronized(identifiedLock) {
                isIdentified = true
            }

            capture(
                "\$identify",
                distinctId = distinctId,
                properties = props,
                userProperties = userProperties,
                userPropertiesSetOnce = userPropertiesSetOnce,
            )

            // We keep the AnonymousId to be used by decide calls and identify to link the previousId
            if (previousDistinctId.isNotBlank()) {
                this.anonymousId = previousDistinctId
            } else {
                config?.logger?.log("identify called with invalid former distinctId: $previousDistinctId.")
            }
            this.distinctId = distinctId

            // only because of testing in isolation, this flag is always enabled
            if (reloadFeatureFlags) {
                reloadFeatureFlags()
            }
        } else {
            config?.logger?.log("already identified with id: $distinctId.")
        }
```
https://github.com/PostHog/posthog-android/blob/bd1ec53504cd174cf335a34c9bef89ccbedb9099/posthog/src/main/java/com/posthog/PostHog.kt#L559-L588

**Comment by marandaneto** [comment] 2024-11-12 07:18
You're right, it was unclear from your first messages that you're calling identify with the same distinct id multiple times.
I think we are missing this bits here: https://github.com/PostHog/posthog-js/blob/ba4f3bde44607f99a3ff63e7985d783b2a184ee8/src/posthog-core.ts#L1384-L1385

You can as a workaround do [this](https://posthog.com/docs/product-analytics/person-properties#how-to-set-person-properties) for now.

```dart
await Posthog().identify(userId: 'test_id', userProperties: {'family_id': '1'});
await Posthog().capture(
  eventName: '$set', 
  properties: {'$set': {'family_id': '2'}} // or $set_once for userPropertiesSetOnce
);
```

**Comment by marandaneto** [comment] 2024-11-12 07:40
Fixes are WIP
* [Android](https://github.com/PostHog/posthog-android/pull/205)

**Comment by marandaneto** [comment] 2024-11-13 07:46
@choim4389 if you upgrade your cocoapods, and generate a new build, this should be fixed.

**Closed by marandaneto** 2024-11-13 07:46 UTC
Labels: bug, Product Analytics

**Comment by choim4389** [comment] 2024-11-19 05:08
Isn't it being distributed as 4.6.1?

**Comment by marandaneto** [comment] 2024-11-19 08:39
> Thanks! I verified that it works. Isn't it being distributed as 4.6.1?

The changes were on the Native SDKs (android and iOS), so the Flutter SDK picks up the latest compatible version.
We only bump the flutter SDK if there are breaking changes on the native SDKs or changes on the dart code.
